-- 1. 공통_지식목록
create TABLE TB_KMS_LIST
(
	KNOW_ID 		INT							COMMENT	'지식ID',
    LAST_CHNGR_ID 	VARCHAR(10)					COMMENT '최종변경자ID',
    LAST_CHNG_DTMD 	DATETIME					COMMENT '최종변경일시',
    FST_REGR_ID 	VARCHAR(10)					COMMENT '최초등록자',
    FST_REG_DTMD	DATETIME					COMMENT '최초등록일시',
    KNOW_TITLE_NM	VARCHAR(100)	NOT NULL	COMMENT '지식제목명',
    MAIN_EXPSE_YN	VARCHAR(1)					COMMENT '메인노출여부',		
    MOBL_USE_YN		VARCHAR(1)					COMMENT '모바일사용여부',
    BLTN_START_DT	VARCHAR(8)		NOT NULL	COMMENT '게시시작일자',
    BLTN_END_DT		VARCHAR(8)		NOT NULL	COMMENT '게시종료일자', 
    KNOW_STS_CD		VARCHAR(2)					COMMENT '지식상태코드',
    KNOW_STS_CHNG_DTMD	DATETIME	NOT NULL	COMMENT '지식상태변경일시',
    KNOW_REG_USERID	VARCHAR(10)		NOT NULL	COMMENT '지식등록사용자ID',
    BRWS_CCNT		INT							COMMENT '조회건수',	
    KNOW_TAG_CNTNT	VARCHAR(100)	NOT NULL	COMMENT '지식태그내용',
    KNOW_CNTNT		TEXT			NOT NULL	COMMENT '지식내용',

	PRIMARY KEY(KNOW_ID)
);

-- 2. 공통_지식첨부파일내역
CREATE TABLE TB_KMS_ATTCH
(
	KNOW_ID					INT							COMMENT '지식ID',
    KNOW_ATAC_FILE_SEQ		int							COMMENT '지식첨부파일순번',
    LAST_CHNGR_ID			VARCHAR(10)					COMMENT '최종변경자ID',
    LAST_CHNG_DTMD			DATETIME					COMMENT '최종변경일시',
    FST_REGR_ID				VARCHAR(10)					COMMENT '최초등록자',
    FST_REG_DTMD			DATETIME					COMMENT '최초등록일시',
    FILE_NM					VARCHAR(100)	NOT NULL	COMMENT '파일명',
    FILE_EXTS_NM			VARCHAR(10)		NOT NULL	COMMENT '파일확장자명',
    FILE_SIZE				INT							COMMENT '파일크기',
    FILE_PATH_NM			VARCHAR(100)	NOT NULL	COMMENT '파일경로명',
    ORGL_FILE_NM			VARCHAR(100) 	NOT NULL 	COMMENT '원본파일명',
    
    PRIMARY KEY(KNOW_ID, KNOW_ATAC_FILE_SEQ)
);

-- 3. 공통_지식경로내역
CREATE TABLE TB_KMS_CATEGORY
(
	KNOW_ID				INT 					COMMENT '지식ID',
    MENU_ID				VARCHAR(10) 			COMMENT '메뉴ID',
    LAST_CHNGR_ID		VARCHAR(10) 			COMMENT '최종변경자ID',
    LAST_CHNG_DTMD		DATETIME 				COMMENT '최종변경일시',
    FST_REGR_ID 		VARCHAR(10)				COMMENT '최초등록자ID',
    FST_REG_DTMD		DATETIME				COMMENT '최초등록일시',
    USE_YN				VARCHAR(1) 				COMMENT '사용여부',
    USE_YN_CHNG_DTMD 	DATETIME	NOT NULL	COMMENT '사용여부변경일시',
    
    PRIMARY KEY(KNOW_ID, MENU_ID)
);

-- 4. 공통_지식검토내역
CREATE TABLE TB_KMS_EXMN
(
	KNOW_ID					INT 						COMMENT '지식ID',
    AUTHZ_REQ_DTM			DATETIME		NOT NULL	COMMENT '승인요청일시',
    LAST_CHNGR_ID			VARCHAR(10) 				COMMENT '최종변경자ID',
    LAST_CHNG_DTMD			DATETIME					COMMENT '최종변경일시',
    FST_REGR_ID				VARCHAR(10)					COMMENT '최초등록자ID',
    FST_REG_DTMDT			DATETIME					COMMENT '최초등록일시',
    KNOW_STS_CD				VARCHAR(2)					COMMENT '지식상태코드',
    AUTHZ_REQ_USERID		VARCHAR(10)		NOT NULL	COMMENT '승인요청사용자ID',
    KNOW_RVW_CFM_DTMD		DATETIME		NOT NULL	COMMENT '지식검토확인일시',
    KNOW_RVW_FINSH_DTMD		DATETIME		NOT NULL    COMMENT '지식검토완료일시',
    KNOW_RVW_USERID			VARCHAR(10)		NOT NULL	COMMENT '지식검토사용자ID',
    KNOW_RVW_SUGG_CNTNT		VARCHAR(1000)	NOT NULL 	COMMENT '지식검토의견내용',
    
    PRIMARY KEY(KNOW_ID, AUTHZ_REQ_DTM)
);

-- 5. 공통_지식즐겨찾기내역alter
CREATE TABLE TB_KMS_BMARK
(
	USERID					VARCHAR(10)  				COMMENT	'사용자ID',
    KNOW_ID					INT							COMMENT '지식ID',
    LAST_CHNGR_ID			VARCHAR(10)					COMMENT '최종변경자ID',
    LAST_CHNGR_DTMD			DATETIME					COMMENT '최종변경일시',
    FST_REGR_ID				VARCHAR(10)					COMMENT '최초등록자ID',
    FST_REG_DTMD			DATETIME		 			COMMENT '최초등록일시',
    BMARK_SEQ				INT				NOT NULL	COMMENT '즐겨찾기순번',
    
    PRIMARY KEY(USERID, KNOW_ID)
);

-- 6. 공통 불만키워드목록
CREATE TABLE TB_KMS_DSAT
(
	DSAT_KEYWD_ID		INT							COMMENT '불만키워드ID',
    LAST_CHNGR_ID		VARCHAR(10)					COMMENT '최종변경자ID',
    LAST_CHNGR_DTMD		DATETIME					COMMENT	'최종변경일시',
    FST_REGR_ID			VARCHAR(10)					COMMENT '최초등록자ID',
    FST_REG_DTMD		DATETIME				 	COMMENT '최초등록일시',
    DSAT_KEYWD_CL_CD	VARCHAR(2) 				 	COMMENT '불만키워드구분코드',
    DSAT_KEYWD_NM		VARCHAR(20) 	NOT NULL 	COMMENT '불만키워드명',
    
    PRIMARY KEY(DSAT_KEYWD_ID)
);